"use client"

import { useState, useEffect, Suspense } from "react"
import { useParams } from "next/navigation"
import api from "@/lib/api"
import { SchemaFormBuilder } from "@/components/tools/schema-form-builder"
import { toast } from "sonner"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { AlertCircle, CheckCircle2 } from "lucide-react"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { AdvancedResultRenderer } from "@/components/advanced-result-renderer"

interface Tool {
    id: string
    name: string
    description: string
    category: string
    versions: any[]
}

export default function ToolExecutionPage() {
    const params = useParams()
    const id = params.id as string

    const [tool, setTool] = useState<Tool | null>(null)
    const [isLoading, setIsLoading] = useState(true)
    const [isExecuting, setIsExecuting] = useState(false)
    const [result, setResult] = useState<any>(null)
    const [error, setError] = useState<string | null>(null)

    useEffect(() => {
        if (id) fetchTool()
    }, [id])

    const fetchTool = async () => {
        try {
            const res = await api.get(`/tools/${id}`)
            setTool(res.data)
        } catch (error) {
            toast.error("Failed to load tool")
            setError("Tool not found or access denied.")
        } finally {
            setIsLoading(false)
        }
    }

    const handleExecute = async (formData: any) => {
        setIsExecuting(true)
        setResult(null)
        setError(null)

        try {
            const res = await api.post(`/tools/${id}/execute`, { input: formData })
            setResult(res.data)
            toast.success("Execution completed successfully!")
        } catch (err: any) {
            console.error(err)
            const msg = err.response?.data?.message || "Execution failed. Please try again."
            setError(msg)
            toast.error("Execution failed")
        } finally {
            setIsExecuting(false)
        }
    }

    if (isLoading) return <div className="p-8 text-center text-muted-foreground">Loading tool...</div>
    if (error && !tool) return <div className="p-8 text-center text-red-500 font-medium">{error}</div>
    if (!tool) return null

    const activeVersion = tool.versions && tool.versions[0]

    return (
        <div className="max-w-4xl mx-auto space-y-8 pb-20">
            <div className="space-y-4 text-center lg:text-left">
                <div className="flex items-center justify-center lg:justify-start gap-3">
                    <h1 className="text-3xl font-bold tracking-tight">{tool.name}</h1>
                    <Badge variant="outline">{tool.category}</Badge>
                </div>
                {activeVersion && <Badge variant="secondary" className="text-xs">v{activeVersion.versionNumber}</Badge>}
                <p className="text-muted-foreground text-lg max-w-2xl">{tool.description || "No description provided."}</p>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-5 gap-8">
                {/* Input Section */}
                <Card className="lg:col-span-2 h-fit">
                    <CardHeader>
                        <CardTitle>Configure Inputs</CardTitle>
                        <CardDescription>Provide the necessary data for the AI.</CardDescription>
                    </CardHeader>
                    <CardContent>
                        {activeVersion ? (
                            <SchemaFormBuilder
                                schema={activeVersion.inputSchema}
                                onSubmit={handleExecute}
                                isExecuting={isExecuting}
                            />
                        ) : (
                            <Alert variant="destructive">
                                <AlertCircle className="h-4 w-4" />
                                <AlertTitle>Unavailable</AlertTitle>
                                <AlertDescription>This tool has no active versions published.</AlertDescription>
                            </Alert>
                        )}
                    </CardContent>
                </Card>

                {/* Output Section */}
                <Card className="lg:col-span-3 min-h-[400px] flex flex-col">
                    <CardHeader>
                        <CardTitle>Result</CardTitle>
                        <CardDescription>The output generated by the AI will appear here.</CardDescription>
                    </CardHeader>
                    <CardContent className="flex-1 flex flex-col">
                        {isExecuting ? (
                            <div className="flex-1 flex flex-col items-center justify-center space-y-4 text-muted-foreground animate-pulse leading-snug">
                                <Loader2Icon className="h-8 w-8 animate-spin text-primary" />
                                <p>Processing your request...</p>
                            </div>
                        ) : result ? (
                            <AdvancedResultRenderer result={result} />
                        ) : (
                            <div className="flex-1 flex items-center justify-center text-muted-foreground/50 border-2 border-dashed rounded-lg">
                                Waiting for execution...
                            </div>
                        )}

                        {error && !isExecuting && (
                            <Alert variant="destructive" className="mt-4">
                                <AlertCircle className="h-4 w-4" />
                                <AlertTitle>Error</AlertTitle>
                                <AlertDescription>{error}</AlertDescription>
                            </Alert>
                        )}
                    </CardContent>
                </Card>
            </div>
        </div>
    )
}

function Loader2Icon(props: any) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M21 12a9 9 0 1 1-6.219-8.56" />
        </svg>
    )
}
